org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
# Opt out of newDsl to fix Flutter Gradle plugin issues with AGP 9+
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false
